name: heart-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - flake8
      - pytest
      - mltable
      - azureml-fsspec
      - joblib
      - pyarrow
      - pandas
      - numpy
      - scikit-learn
      - mlflow
      - azureml-mlflow
      - matplotlib
      - seaborn