$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command

code: ../
command: >
  python src/train.py
  --experiment-name heart-disease-training
  --data_path ${{inputs.heart_data}}
  --artifacts ${{outputs.artifacts}}

environment: azureml:heart-env@latest

compute: azureml:ag-aiml-compute

experiment_name: heart-disease-training
description: Train Logistic Regression and Random Forest models for heart disease prediction

inputs:
  heart_data:
    type: uri_file
    path: azureml:heart-csv:1


outputs:
  best_model:
    type: uri_folder
    mode: upload
    path: azureml://datastores/workspaceblobstore/paths/heart-model/

  artifacts:
    type: uri_folder
    mode: upload
    path: azureml://datastores/workspaceblobstore/paths/heart-model/

